///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BasicPortalPage.Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestRegistration recording.
    /// </summary>
    [TestModule("722f6a71-c163-43a3-89e7-1a6d1b704811", ModuleType.Recording, 1)]
    public partial class TestRegistration : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BasicPortalPage.BasicPortalPageRepository repository.
        /// </summary>
        public static global::BasicPortalPage.BasicPortalPageRepository repo = global::BasicPortalPage.BasicPortalPageRepository.Instance;

        static TestRegistration instance = new TestRegistration();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestRegistration()
        {
            Username = "";
            Password = "";
            ConfirmPassword = "";
            Email = "";
            FirstName = "";
            LastName = "";
            Telefon = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestRegistration Instance
        {
            get { return instance; }
        }

#region Variables

        string _Username;

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("9ba0ae2e-804e-4fd8-ad31-60dec8043836")]
        public string Username
        {
            get { return _Username; }
            set { _Username = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("007abc86-85ab-4a69-8f8b-9964edf14a64")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        string _ConfirmPassword;

        /// <summary>
        /// Gets or sets the value of variable ConfirmPassword.
        /// </summary>
        [TestVariable("9dd69635-10ea-4353-8f23-de4f10f909e4")]
        public string ConfirmPassword
        {
            get { return _ConfirmPassword; }
            set { _ConfirmPassword = value; }
        }

        string _Email;

        /// <summary>
        /// Gets or sets the value of variable Email.
        /// </summary>
        [TestVariable("f6194240-28f8-4427-b6b3-a47c3f9239a6")]
        public string Email
        {
            get { return _Email; }
            set { _Email = value; }
        }

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("801cd2fa-d709-49e6-95d8-322400050260")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("07211bc2-cb48-4452-b6ea-0278d1ce1a1e")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        string _Telefon;

        /// <summary>
        /// Gets or sets the value of variable Telefon.
        /// </summary>
        [TestVariable("504ca84a-a284-4c20-beae-b023de2718e2")]
        public string Telefon
        {
            get { return _Telefon; }
            set { _Telefon = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VectorworksCloudServices.LoginAndRegistration.VCSLogin.VCS_SignIn_button' at Center.", repo.VectorworksCloudServices.LoginAndRegistration.VCSLogin.VCS_SignIn_buttonInfo, new RecordItemIndex(1));
            repo.VectorworksCloudServices.LoginAndRegistration.VCSLogin.VCS_SignIn_button.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.DoNotHaveAccount' at Center.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.DoNotHaveAccountInfo, new RecordItemIndex(3));
            //repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.DoNotHaveAccount.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Username' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.Username'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.UsernameInfo, new RecordItemIndex(4));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.Username.PressKeys(Username);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.Password'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.PasswordInfo, new RecordItemIndex(5));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.Password.PressKeys(Password);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ConfirmPassword' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.ConfirmPassword'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.ConfirmPasswordInfo, new RecordItemIndex(6));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.ConfirmPassword.PressKeys(ConfirmPassword);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Email' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.Email'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.EmailInfo, new RecordItemIndex(7));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.Email.PressKeys(Email);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstName' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.FirstName'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.FirstNameInfo, new RecordItemIndex(8));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.FirstName.PressKeys(FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.LastName'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.LastNameInfo, new RecordItemIndex(9));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Register.LastName.PressKeys(LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Telefon' with focus on 'VectorworksCloudServices.LoginAndRegistration.SSO_Page.Phone'.", repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.PhoneInfo, new RecordItemIndex(10));
            repo.VectorworksCloudServices.LoginAndRegistration.SSO_Page.Phone.PressKeys(Telefon);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
